version: '3.7'
services:
    rabbitmq:
        build: ./
        ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
        privileged: true
        environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        hostname: laradock-rabbitmq
        volumes:
        - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq
        networks:
        - backend
networks:
   backend: